add consumer controller
subquery/network-contracts pull request #201
Opened 2023-06-07 23:23 UTC by Jianzhuo

2023-06-07 23:37 UTC, nz-neo commented on contracts/ConsumerHost.sol
> +    mapping(address => address) private consumerController;
why need two mapping ? 
If we just use `consumerControllers`, when checkSign, check the `sConsumer` is consumer self (`channels[channelId]`), or `consumerControllers[consumer]`

2023-06-08 01:01 UTC, nz-neo approved these changes

2023-06-08 01:01 UTC, nz-neo commented
Add unit tests for it

2023-06-08 03:41 UTC, ianhe8x requested changes
more unit tests

2023-06-21 00:25 UTC, nz-neo approved these changes

2023-06-21 01:23 UTC, merged