Add min limit when add/remove booster
subquery/network-contracts pull request #416
Opened 2024-06-26 23:38 UTC by nz-neooo

2024-06-30 23:39 UTC, ianhe8x requested changes

2024-06-30 23:39 UTC, ianhe8x commented on contracts/RewardsBooster.sol
> +        require(deploymentPool.boosterPoint >= minimumDeploymentBooster, 'RB015');
I thought you should check `deploymentPool.accountBooster[_account]`

2024-06-30 23:39 UTC, ianhe8x commented on contracts/RewardsBooster.sol
> +        require(deploymentPool.boosterPoint >= minimumDeploymentBooster, 'RB015');
can you add a test to cover this scenaio? when there is boost bigger than min for a deployment and a user tries to add boost smaller than min, it should fail.

2024-06-30 23:40 UTC, ianhe8x commented
@nz-neooo what do you think of `can not get booster reward if boosted token less than minimum`, since now it is impossible except for existing boosters. Should we remove this amount check in the contract?

2024-07-01 01:37 UTC, nz-neooo commented
Now it's limited to the total deployment booster. If we want to apply "minimum", limited to the account will be simple and clear.

2024-07-03 00:10 UTC, ianhe8x approved these changes

2024-07-03 01:12 UTC, merged